Repository anita00001/fix-mate-frontend, pull requests merged in 2023-11, with the labels that each got.

#15 Sidebar desktop
  src/components/Sidebar.js
  src/styles/sideBar.css
Labels: frontend

#17 Expert page
  package-lock.json
  package.json
  src/App.js
  src/components/Experts.js
  src/index.js
  src/redux/Experts/ExpertsSlice.js
  src/redux/store.js
  src/styles/Experts.css
Labels: frontend

#18 Reservations list page
  package-lock.json
  package.json
  public/images/fix-background.jpg
  public/images/kenny-eliason-unsplash.jpg
  src/App.js
  src/components/Authenticate.js
  src/components/Experts.js
  src/components/Reservations.js
  src/components/Sidebar.js
  src/components/SignupForm.js
  src/components/loginForm.js
  src/index.css
  src/index.js
  src/redux/Experts/expertsSlice.js
  src/redux/Reservations/reservationsSlice.js
  src/redux/apiConfig.js
  src/redux/login/loginSlice.js
  src/redux/signup/signupSlice.js
  src/redux/store.js
  src/styles/Experts.css
  tailwind.config.js
Labels: frontend

#19 Create a new Expert
  src/App.js
  src/components/CreateExpert.js
  src/components/Sidebar.js
  src/styles/Experts.css
Labels: frontend

#22 Expert details
  .prettierrc
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/components/ExpertDetails.jsx
  src/components/Experts.js
Labels: frontend

#23 Refactor code
  src/App.js
  src/components/CreateExpert.js
  src/components/Experts/CreateExpert/CreateExpert.jsx
  src/components/Experts/CreateExpert/CreateExpertForm.jsx
  src/components/Experts/DeleteExpert/DeleteExpert.jsx
  src/components/Experts/DeleteExpert/DeleteExpertTable.jsx
  src/components/Experts/Experts&Details/Expert.jsx
  src/components/Experts/Experts&Details/ExpertDetails.jsx
  src/components/Main/Home.jsx
  src/components/Navigation/Sidebar.jsx
  src/components/Navigation/index.js
  src/components/Reservations.js
  src/components/Reservations/Reservations.jsx
  src/components/Reservations/index.js
  src/components/UsersLogin/Authenticate.js
  src/components/UsersLogin/SignupForm.js
  src/components/UsersLogin/loginForm.js
Labels: frontend

#24 Experts-slider
  package-lock.json
  package.json
  src/components/Experts/Experts&Details/Expert.jsx
  src/components/Navigation/Sidebar.jsx
  src/components/UsersLogin/SignupForm.js
  src/components/UsersLogin/loginForm.js
  src/index.css
  src/styles/sideBar.css
  src/styles/swiperCustom.css
Labels: frontend

#27 Styling
  package-lock.json
  package.json
  public/images/bg.jpg
  public/images/demo.jpg
  src/components/Experts/CreateExpert/CreateExpert.jsx
  src/components/Experts/CreateExpert/CreateExpertForm.jsx
  src/components/Experts/DeleteExpert/DeleteExpert.jsx
  src/components/Experts/DeleteExpert/DeleteExpertTable.jsx
  src/components/Experts/Experts&Details/Expert.jsx
  src/components/Experts/Experts&Details/ExpertDetails.jsx
  src/components/Navigation/Sidebar.jsx
  src/components/Specializations/Specialize.js
  src/styles/sideBar.css
  src/styles/swiperCustom.css
Labels: frontend

#26 Specialization dropdown
  src/components/Experts/CreateExpert/CreateExpertForm.jsx
  src/components/Specializations/SpecializationDropdown.js
  src/components/Specializations/Specialize.js
  src/redux/Experts/expertsSlice.js
  src/redux/Specializations/specialitiesSlice.js
Labels: enhancement

#28 Add image
  src/components/Experts/CreateExpert/CreateExpert.jsx
  src/components/Experts/CreateExpert/CreateExpertForm.jsx
  src/components/Experts/Experts&Details/Expert.jsx
  src/components/Experts/Experts&Details/ExpertDetails.jsx
  src/components/Specializations/SpecializationDropdown.js
Labels: frontend

#30 Styling
  package-lock.json
  package.json
  src/assets/Fixmate.jpeg
  src/assets/gallery.jpeg
  src/assets/login.jpeg
  src/assets/signup.jpeg
  src/components/Experts/CreateExpert/CreateExpert.jsx
  src/components/Experts/CreateExpert/CreateExpertForm.jsx
  src/components/Experts/DeleteExpert/DeleteExpert.jsx
  src/components/Experts/DeleteExpert/DeleteExpertTable.jsx
  src/components/Experts/Experts&Details/Expert.jsx
  src/components/Experts/Experts&Details/ExpertDetails.jsx
  src/components/Main/Home.jsx
  src/components/Navigation/Sidebar.jsx
  src/components/Reservations/ReservationForm.js
  src/components/Reservations/ReservationFormDetails.js
  src/components/Reservations/Reservations.jsx
  src/components/Reservations/index.js
  src/components/Specializations/SpecializationDropdown.js
  src/components/Specializations/Specialize.js
  src/components/UsersLogin/Authenticate.js
  src/components/UsersLogin/SignupForm.js
  src/components/UsersLogin/loginForm.js
  src/styles/main.css
  tailwind.config.js
Labels: frontend

#32 License and Documentation
  LICENSE
  README.md
  README.old.md
Labels: documentation
